import "../style/globals.css";
import NextAuthProvider from "@/Providers/NextAuthProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <div className="container m-auto py-10 px-5">
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
