import localFont from "next/font/local";
import "../style/globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container m-auto py-10 px-5">
          {children}
        </div>
      </body>
    </html>
  );
}
